version: '3.8'
services:
  postgres:
    container_name: 'database'
    image: 'postgres'
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=POSTGRES_DATABASE
